Capstone1: Artfifcial Intelligence and Iot forum
GedeonTS/Artficial-intelligence-forum pull request #1
Opened 2022-04-14 07:05 UTC by GedeonTS

#  Artificial Intelligence and IoT forum

In this project, I created a responsive and dynamic webpage using Html, css, and javascript.

your review is welcome!

2022-04-15 12:55 UTC, sja-thedude requested changes
Hi @GedeonTS, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Suggested changes
- [ ] Good Video presentation. 👍 But I find some images were not displayed when I tried your website by cloning or with your Github page deploy. I see you gave the presentation via firefox. Kindly make sure that the website works fine on chrome as its default browser for most and is used by everyone.
- [ ] _Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-04-15 12:55 UTC, sja-thedude commented on README.md
> +
- [x] Kindly make sure to add an "Acknowledgements" section or similar that gives appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

2022-04-15 12:55 UTC, sja-thedude commented on README.md
> +Click [here](https://gedeonts.github.io/Artificial-intelligence-forum/)
- [x] Kindly fix this. This link is broken.

2022-04-15 12:55 UTC, sja-thedude commented on index.html
> +      </div>
- [ ] Kindly add the top dark navbar which contains the social media icons and the logout button aligned to the right as per the original design. Also make sure to place this in `nav` tags.

<img width="876" alt="Screenshot 2022-04-15 at 2 42 59 PM" src="https://user-images.githubusercontent.com/70269507/163567392-e76d06e0-55f2-4f7c-8dc1-c373376c4c96.png">

- [ ] Kindly make sure that the background colour of the hamburger menu is the same as the colours used on the home page. 

<img width="498" alt="Screenshot 2022-04-15 at 2 41 17 PM" src="https://user-images.githubusercontent.com/70269507/163567436-2ed3e1c9-83d9-4038-82ad-eb80e7278b5c.png">

2022-04-15 12:55 UTC, sja-thedude commented on index.html
> +            </div>
- [ ] Kindly make sure to align the logo to the left as per the original design.
<img width="1262" alt="Screenshot 2022-04-15 at 2 58 10 PM" src="https://user-images.githubusercontent.com/70269507/163568156-1f5f5f98-d76e-44a6-9e7c-1f6550ebe657.png">

2022-04-15 12:55 UTC, sja-thedude commented on about-page.html
> +        <h2 class="logo-header font">Partners</h2>
- Kindly uses semantic tags, instead of divs use more of `section` for best practices.

2022-04-15 12:55 UTC, sja-thedude commented on style.css
> +/* media media media media media media media media media media media media media media media media media media  */
- [ ] Kindly remove the commented out code for the clean codebase.

2022-04-15 12:55 UTC, sja-thedude commented on script.js
> +
- [ ] Kindly make sure to add the corner checks background image to all the speakers. The background image is shown in the video you recorded but it is not visible on the Github page you deployed nor when I clone it on my mac.
- [ ] Kindly also follow the spacing and give the appropriate margin as per the original design.
- Original design:
<img width="830" alt="Screenshot 2022-04-15 at 3 21 32 PM" src="https://user-images.githubusercontent.com/70269507/163570094-5400c2b8-eead-4e63-8be9-2d82682f0e60.png">

- Your design:
<img width="1268" alt="Screenshot 2022-04-15 at 3 21 11 PM" src="https://user-images.githubusercontent.com/70269507/163570084-dfa8775b-1660-46b0-9129-13b1349d98c0.png">

2022-04-15 12:55 UTC, sja-thedude commented on index.html
> +              Information on ITU Activities on "Environment, Climate Change and
- [ ] Kindly make sure to follow the background color as per the original design.
- Original design:
<img width="827" alt="Screenshot 2022-04-15 at 3 29 21 PM" src="https://user-images.githubusercontent.com/70269507/163570885-8b01b215-2a04-4e96-9cdd-a850edaeac2c.png">

- Your design:
<img width="1267" alt="Screenshot 2022-04-15 at 3 29 01 PM" src="https://user-images.githubusercontent.com/70269507/163570899-f05c7ee8-76b1-4be4-b9da-8616ac08e1a6.png">

2022-04-15 12:55 UTC, sja-thedude commented on about-page.html
> +          </p>
- [ ] Kindly make sure to follow the background colour as given in the original design and also follow the spacing, font size for the webpage.

- Original design:
<img width="1265" alt="Screenshot 2022-04-15 at 3 33 33 PM" src="https://user-images.githubusercontent.com/70269507/163571291-c416936a-e2e2-4151-96c2-dcde1e24b09a.png">

- Your design:
<img width="736" alt="Screenshot 2022-04-15 at 3 33 53 PM" src="https://user-images.githubusercontent.com/70269507/163571300-49126659-1788-40c6-b7f3-bccb269b371f.png">

2022-04-15 12:55 UTC, sja-thedude commented on index.html
> +            the quality of life of people.
- [ ] Kindly make sure to follow the colour as per the original design for the heading. Use #ec5242.
- [ ] Kindly make sure that the hamburger is of #272a31 colour as per the original design.
- Original design:
<img width="392" alt="Screenshot 2022-04-15 at 3 40 01 PM" src="https://user-images.githubusercontent.com/70269507/163571953-0d46c424-1903-4290-b0de-e5e9c382bd06.png">

- Your design:
<img width="501" alt="Screenshot 2022-04-15 at 3 39 09 PM" src="https://user-images.githubusercontent.com/70269507/163571957-a58d0184-2910-4701-9f1c-0bb4df2e61e2.png">

2022-04-15 12:55 UTC, sja-thedude commented on README.md
> +> This is a Webpage about the international artificial intelligence forum.
- [ ] Kindly add more description of the project like "This is part of microverse curriculum and built for the capstone. This is a simple website that navigates from the home page to the about page. This is responsive and follow mobile first."

2022-04-15 21:16 UTC, alexander16108 approved these changes
Hi, @GedeonTS, 

good job implementing all the requested activities done in the project, 🥳 🍾  congratulations you can move on with the module ✔️ 

In my opinion, your project is ready There is nothing else to say other than... it's time to merge it :shipit: 

<img style="height:50px" src="https://media3.giphy.com/media/Y2bC3o5BkYNndT4vbK/giphy.gif"/>

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-04-15 21:36 UTC, merged

2025-03-05 11:23 UTC, GedeonTS commented on README.md
> +Click [here](https://gedeonts.github.io/Artificial-intelligence-forum/)
Testing thread behaviour